# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('hair_color', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
